- hosts: jenkins-master
  become: yes

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install snapd
      apt:
        name: snapd
        state: present

    - name: Ensure snapd is running
      service:
        name: snapd
        state: started
        enabled: yes

    - name: Install Jenkins via Snap (with classic confinement)
      snap:
        name: jenkins
        state: present
        classic: yes

    - name: Install Java and Docker
      apt:
        name:
          - openjdk-17-jre
        state: present

    - name: Ensure Jenkins service is running
      service:
        name: snap.jenkins.jenkins
        state: started
        enabled: yes